version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: diet-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"
    volumes:
      - diet-mongo-data:/data/db
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  postgres-product:
    image: 'postgres:latest'
    container_name: product-psql
    environment:
      - 'POSTGRES_DB=food'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=dev'
    ports:
      - '5432:5432'
    volumes:
      - product-psql-data:/var/lib/postgresql/data
      - ./postgres/product/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  postgres-meal:
    image: 'postgres:latest'
    container_name: meal-psql
    environment:
      - 'POSTGRES_DB=chef'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=dev'
    ports:
      - '5434:5432'
    volumes:
      - meal-psql-data:/var/lib/postgresql/data
      - ./postgres/meal/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  diet-mongo-data:
  meal-psql-data:
  product-psql-data: