version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: diet-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"
    volumes:
      - diet-data:/data/db
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  postgres:
    image: 'postgres:latest'
    container_name: diet-psql
    environment:
      - 'POSTGRES_DB=diet'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=dev'
    ports:
      - '5432:5432'
    volumes:
      - diet-psql-data:/var/lib/postgresql/data
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  diet-data:
  diet-psql-data: